forge "http://forge.puppetlabs.com"

mod 'puppetlabs/concat', :git => 'https://github.com/puppetlabs/puppetlabs-concat.git', :ref => '1.0.0'
mod "puppetlabs/java"
mod "puppetlabs/mysql"
mod "puppetlabs/apache"
mod "example42/php"
mod "saz/vim"