site:
  css:
    - /resources/thirdparty/travi-styles/css/travi-baseline.css
    - /resources/thirdparty/travi-styles/css/travi-basic.css
  js:
    - framework
  small:
    js:
      - animationFrame
      - /resources/thirdparty/travi-slide-nav/jquery.slideNav.js

entities:
  index:
    css:
      - /resources/thirdparty/travi-styles/css/travi-form.css
    js:
      - /resources/thirdparty/travi-ui/js/dialog/simple.js
      - /resources/thirdparty/travi-ui/js/dialog/conventions.js