site:
  css:
    - /resources/thirdparty/travi-styles/dist/css/core/travi-basic.css
  js:
    - framework
  small:
    js:
      - animationFrame
      - /resources/thirdparty/travi-slide-nav/jquery.slideNav.js